# == Классический ==
# Это упрощённый способ переопределить некоторые опции для обратной совместимости
# с `ls`. Влияет на опции "color"->"when", "sorting"->"dir-grouping", "date"
# и "icons"->"when".
# Возможные значения: false, true
classic: false

# == Колонки ==
# Определяет, какие колонки и в каком порядке использовать в длинном и древовидном
# представлении.
# Возможные значения: permission, user, group, context, size, date, name, inode, links, git
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

# == Цвет ==
# Настройки цвета. (Будет расширено в будущем.)
color:
  # Когда окрашивать вывод.
  # Если "classic" установлен, будет "never".
  # Возможные значения: never, auto, always
  when: auto
  # Как окрашивать вывод.
  # Если "classic" установлен, будет "no-color".
  # Возможные значения: default, custom
  # Если "custom", lsd будет искать colors.yaml в директории конфигурации.
  theme: default

# == Дата ==
# Определяет формат даты для колонки даты. Формат задаётся как strftime.
# Если "classic" установлен, будет "date".
# Возможные значения: date, locale, relative, '+<date_format>'
# `date_format` — это формат strftime, например '+%d %b %y %X' даст: 17 Jun 21 20:14:55
date: date

# == Следовать ссылкам ==
# Следовать ли символическим ссылкам.
# Возможные значения: false, true
dereference: false

# == Отображение ==
# Какие элементы показывать. Не указывайте для поведения по умолчанию.
# Возможные значения: all, almost-all, directory-only
# display: all

# == Иконки ==
icons:
  # Когда использовать иконки.
  # Если "classic" установлен, будет "never".
  # Возможные значения: always, auto, never
  when: auto
  # Какую тему иконок использовать.
  # Возможные значения: fancy, unicode
  theme: fancy
  # Разделитель между иконкой и именем
  # По умолчанию — один пробел
  separator: " "

# == Игнорируемые шаблоны ==
# Список шаблонов, которые нужно игнорировать при выводе.
# ignore-globs:
#   - .git

# == Индикаторы ==
# Добавлять ли специальные символы к определённым файлам.
# Возможные значения: false, true
indicators: false

# == Макет ==
# Какой макет использовать. "oneline" может быть немного запутанным, возможно,
# будет переименован в "one-per-line".
# Возможные значения: grid, tree, oneline
layout: grid

# == Рекурсия ==
recursion:
  # Включить рекурсию или нет.
  # Возможные значения: false, true
  enabled: false
  # На какую глубину рекурсировать. Должно быть положительным числом. 
  # Если не указано — (практически) бесконечно.
  # depth: 3

# == Размер ==
# Формат колонки размера.
# Возможные значения: default, short, bytes
size: default

# == Права ==
# Формат колонки прав доступа
# Возможные значения: rwx, octal, attributes (только Windows), disable
# permission: rwx

# == Сортировка ==
sorting:
  # По чему сортировать.
  # Возможные значения: extension, name, time, size, version
  column: name
  # Обратить порядок сортировки.
  # Возможные значения: false, true
  reverse: false
  # Группировать ли директории и где.
  # Если "classic" установлен, будет "none".
  # Возможные значения: first, last, none
  dir-grouping: none

# == Без символических ссылок ==
# Пропускать ли отображение целей символических ссылок
# Возможные значения: false, true
no-symlink: false

# == Общий размер ==
# Показывать ли общий размер директорий.
# Возможные значения: false, true
total-size: false

# == Гиперссылка ==
# Добавлять гиперссылку к именам файлов
# Возможные значения: always, auto, never
hyperlink: never

# == Стрелка для символьной ссылки ==
# Как отображать стрелку для ссылок, символы в ASCII и UTF-8
symlink-arrow: ⇒

# == Заголовок ==
# Показывать ли заголовки колонок.
# Возможные значения: false, true
header: false

# == Литерально ==
# Показывать ли кавычки вокруг имён файлов.
# Возможные значения: false, true
literal: false

# == Усечение владельца ==
# Как усекать имена пользователя и группы, если они слишком длинные.
truncate-owner:
  # Количество символов для оставления. По умолчанию усечения нет.
  after:
  # Строка, добавляемая при усечении
  marker: ""
